### ISSUE TITLE
IPR - Maintenance Application development

### ISSUE THREAD

**Issue by raju-kurup** [astpl1998/IPR#1]
We want to develop Maintenance Application with all features with mobile usability.
[IPR-Maintenance Project Plan.pptx](https://github.com/astpl1998/IPR/files/3038885/IPR-Maintenance.Project.Plan.pptx)

**Comment by Prabakaran92** [comment]
Dear sir,
Basic observation of EAM screen Development
[Enterprise asset management.docx](https://github.com/astpl1998/IPR/files/3043482/Enterprise.asset.management.docx)

Regards,
Prabakaran A

**Comment by maheshwaran-m** [comment]
IPR- Screens and Fields design.
[IPR fields design-Mobile.pptx](https://github.com/astpl1998/IPR/files/3130094/IPR.fields.design-Mobile.pptx)

**Comment by raju-kurup** [comment]
Issue is transferred to IPR XPSERV repository
